:doctype: article
:icons: font
:source-highlighter: highlightjs
:docname: Javascript SDK





++++

<div align="center">

<h1>Contributing to Modzy's Javascript SDK</h1>

<br>
<br>
<br>
<br>



<img alt="GitHub contributors" src="https://img.shields.io/github/contributors/modzy/sdk-javascript">

<img alt="GitHub last commit" src="https://img.shields.io/github/last-commit/modzy/sdk-javascript">

<img alt="GitHub Release Date" src="https://img.shields.io/github/release-date/modzy/sdk-javascript">

<br>
<br>

<img src="https://img.shields.io/badge/Contributor%20Covenant-v2.0%20adopted-ff69b4.svg" alt="Contributor Covenant" style="max-width:100%;">

</div>

<br>
<br>

<div align="center">
<a href="/README.md" style="text-decoration:none">Readme</a> |
<a href=https://docs.modzy.com/docs style="text-decoration:none">Documentation</a>

</div>

<br>
<br>
<br>
<br>

++++

Contributions are welcome and they are greatly appreciated! Every little bit helps, and credit will always be given.

Below you'll find our contributing requirements, a step-by-step guideline, and our features roadmap.


== Requirements

- Search previous link:https://github.com/modzy/sdk-javascript/issues[issues] before making new ones to avoid duplicates.
- If you are reporting a bug, please include:
  . Your operating system name and version.
  . Any details about your local setup that might be helpful in troubleshooting.
  . Detailed steps to reproduce the bug.
- If you are proposing a feature:
  . Explain in detail how it would work.
  . Keep the scope as narrow as possible, to make it easier to implement.
  . Remember that this is a volunteer-driven project, and that contributions are welcome.
- File an issue to let us know what you're working on.
- Fork the repo, develop and test your code changes, and add supporting documentation.
- Use descriptive comments throughout your code.
- Add test cases and comment them.
//- Check your spelling and grammar.
- Use descriptive commit messages that clearly explain the changes. Reference the original issue in the pull request.
- Make an individual pull request for each issue.



== Guidelines


=== 1. Fork the repo and set it for local development

Clone the repository:

- `$ git clone https://github.com/modzy/sdk-javascript.git`

Install dependencies:

- `$ yarn install` or `$ npm install`

Create a branch for your awesome new feature:

- `$ git checkout -b my-awesome-new-feature`


=== 2. Develop your changes

Fix that bug or build your feature.

=== 3. Run unit tests

Configure the environment variables to easily run all the tests with a single configuration point.

You can:

==== Set environment variables in bash

===== Windows

[source,bash]
----
set MODZY_BASE_URL=http://modzy.com/api
set MODZY_API_KEY=my_key.modzy
----

===== Unix

[source,bash]
----
export MODZY_BASE_URL=http://modzy.com/api
export MODZY_API_KEY=my_key.modzy
----

==== Use `.env` file

Create a `.env` file in the root folder with your API key:

[source,js]
----
MODZY_BASE_URL=http://modzy.com/api
MODZY_API_KEY=my_key.modzy

----

Run tests:

- `$ yarn test` or `$ npm test`

Or specify the test that you want to run:

- `$ yarn test -- model-client.test.js`

With npm:

- `$ npm test -- model-client.test.js`

=== 4. Document your changes

Add supporting documentation for your code.

=== 5. Transpile the code

- `$ yarn build` or `$ npm run-script build`

=== 6. Send a pull request

Add and commit your changes:

- `git add .`

- `$ git commit "A descriptive message"`

Push your branch to GitHub:

- `$ git push origin my-new-awesome-feature`

//== Code of conduct

== Roadmap

- Wider API coverage (custom models, accounting, audit, etc).
- [Maybe] Add retry logic for possibly transient issues.
- Fetch model list errors.

== Support

Use GitHub to report bugs and send feature requests. +
Reach out to https://www.modzy.com/support/ for support requests.
